In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('max_columns',100)

In [2]:
df = pd.read_csv("data/train.csv")
print(df.shape)
df.head()

(14095, 54)

,ID,COMPONENT_ARBITRARY,ANONYMOUS_1,YEAR,SAMPLE_TRANSFER_DAY,ANONYMOUS_2,AG,AL,B,BA,BE,CA,CD,CO,CR,CU,FH2O,FNOX,FOPTIMETHGLY,FOXID,FSO4,FTBN,FE,FUEL,H2O,K,LI,MG,MN,MO,NA,NI,P,PB,PQINDEX,S,SB,SI,SN,SOOTPERCENTAGE,TI,U100,U75,U50,U25,U20,U14,U6,U4,V,V100,V40,ZN,Y_LABEL
0,TRAIN_00000,COMPONENT3,1486,2011,7,200,0,3,93,0,0,3059,0.0,0,13,78,NaN,NaN,NaN,NaN,NaN,NaN,888,NaN,0.0,27.0,1,14,16,1,16,6,1951,0,8504,21370,0,427,2,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,154.0,75,0
1,TRAIN_00001,COMPONENT2,1350,2021,51,375,0,2,19,0,0,2978,0.0,0,0,31,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,0.0,NaN,0,1,0,0,1,0,572,2,19,1117,0,0,0,NaN,0,0.0,0.0,1.0,2.0,4.0,6.0,216.0,1454.0,0,NaN,44.0,652,0
2,TRAIN_00002,COMPONENT2,2415,2015,2,200,0,110,1,1,0,17,0.0,0,1,2,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,0.0,0.0,0,0,0,0,2,0,328,0,17,1334,0,0,1,NaN,0,0.0,0.0,0.0,0.0,3.0,39.0,11261.0,41081.0,0,NaN,72.6,412,1
3,TRAIN_00003,COMPONENT3,7389,2010,2,200,0,8,3,0,0,1960,0.0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN,0.0,NaN,0,4,1,0,0,0,906,1,44,21774,2,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,133.3,7,0
4,TRAIN_00004,COMPONENT3,3954,2015,4,200,0,1,157,0,0,71,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,71,NaN,0.0,0.0,0,0,0,0,2,0,309,0,217,18470,0,2,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,133.1,128,0

In [3]:
# show dataframe for each features that we have
dataFeatures = []
dataType     = []
null         = []
nullPCT      = []
unique       = []
minValue     = []
maxValue     = []
uniqueSample = []


for item in list(df):
    dataFeatures.append(item)

for item in dataFeatures:
    dataType.append(df[item].dtype.name)
    
for item in dataFeatures:
    null.append(len(df[df[item].isnull() == True]))

for item in dataFeatures:
    nullPCT.append(round(len(df[df[item].isnull() == True])/len(df[item])*100,2))
    
for item in dataFeatures:
    minValue.append(df[item].min())

for item in dataFeatures:
    maxValue.append(df[item].max())

for item in dataFeatures:
    unique.append(df[item].nunique())

for item in dataFeatures:
    uniqueSample.append(df[item].unique()[0:2])

df_info = pd.DataFrame({
    'dataFeatures' : dataFeatures,
    'dataType' : dataType,
    'null' : null,
    'nullPCT':nullPCT,
    'unique' : unique,
    'minValue' : minValue,
    'maxValue' : maxValue,
    'uniqueSample':uniqueSample
})
df_info

,dataFeatures,dataType,null,nullPCT,unique,minValue,maxValue,uniqueSample
0,ID,object,0,0.00,14095,TRAIN_00000,TRAIN_14094,"[TRAIN_00000, TRAIN_00001]"
1,COMPONENT_ARBITRARY,object,0,0.00,4,COMPONENT1,COMPONENT4,"[COMPONENT3, COMPONENT2]"
2,ANONYMOUS_1,int64,0,0.00,2951,1000,294451,"[1486, 1350]"
3,YEAR,int64,0,0.00,16,2007,2022,"[2011, 2021]"
4,SAMPLE_TRANSFER_DAY,int64,0,0.00,107,0,368,"[7, 51]"
5,ANONYMOUS_2,int64,0,0.00,842,200,9650,"[200, 375]"
6,AG,int64,0,0.00,4,0,3,"[0, 1]"
7,AL,int64,0,0.00,328,0,4630,"[3, 2]"
8,B,int64,0,0.00,504,0,2051,"[93, 19]"
9,BA,int64,0,0.00,38,0,216,"[0, 1]"
10,BE,int64,0,0.00,9,0,9,"[0, 6]"
11,CA,int64,0,0.00,2581,0,6609,"[3059, 2978]"
12,CD,float64,1394,9.89,6,0.0,18.0,"[0.0, nan]"
13,CO,int64,0,0.00,10,0,27,"[0, 1]"
14,CR,int64,0,0.00,102,0,2398,"[13, 0]"
15,CU,int64,0,0.00,496,0,5701,"[78, 31]"
16,FH2O,float64,10205,72.40,72,6.0,320.0,"[nan, 9.0]"
17,FNOX,float64,10205,72.40,21,3.0,38.0,"[nan, 5.0]"
18,FOPTIMETHGLY,float64,10205,72.40,8,0.0,13.0,"[nan, 0.0]"
19,FOXID,float64,10205,72.40,34,4.0,68.0,"[nan, 9.0]"
20,FSO4,float64,10205,72.40,35,10.0,68.0,"[nan, 18.0]"
21,FTBN,float64,10205,72.40,99,0.0,27.7,"[nan, 8.9]"
22,FE,int64,0,0.00,1281,0,31706,"[888, 2]"
23,FUEL,float64,10205,72.40,21,0.0,12.0,"[nan, 0.0]"
24,H2O,float64,0,0.00,47,0.0,52.7,"[0.0, 0.1]"
25,K,float64,2299,16.31,102,0.0,705.0,"[27.0, nan]"
26,LI,int64,0,0.00,36,0,117,"[1, 0]"
27,MG,int64,0,0.00,554,0,1509,"[14, 1]"
28,MN,int64,0,0.00,100,0,877,"[16, 0]"
29,MO,int64,0,0.00,298,0,419,"[1, 0]"
30,NA,int64,0,0.00,83,0,1212,"[16, 1]"
31,NI,int64,0,0.00,57,0,176,"[6, 0]"
32,P,int64,0,0.00,2191,2,3102,"[1951, 572]"
33,PB,int64,0,0.00,73,0,736,"[0, 2]"
34,PQINDEX,int64,0,0.00,1910,0,56761,"[8504, 19]"
35,S,int64,0,0.00,8076,386,64160,"[21370, 1117]"
36,SB,int64,0,0.00,38,0,103,"[0, 2]"
37,SI,int64,0,0.00,514,0,5459,"[427, 0]"
38,SN,int64,0,0.00,37,0,289,"[2, 0]"
39,SOOTPERCENTAGE,float64,10205,72.40,55,0.0,6.5,"[nan, 0.2]"
40,TI,int64,0,0.00,71,0,403,"[5, 0]"
41,U100,float64,11779,83.57,14,0.0,18.0,"[nan, 0.0]"
42,U75,float64,11779,83.57,20,0.0,33.0,"[nan, 0.0]"
43,U50,float64,11779,83.57,90,0.0,939.0,"[nan, 1.0]"
44,U25,float64,11779,83.57,195,0.0,1651.0,"[nan, 2.0]"
45,U20,float64,11779,83.57,275,0.0,2932.0,"[nan, 4.0]"
46,U14,float64,11977,84.97,549,0.0,11296.0,"[nan, 6.0]"
47,U6,float64,11977,84.97,1766,15.0,412627.0,"[nan, 216.0]"
48,U4,float64,11977,84.97,2053,154.0,844421.0,"[nan, 1454.0]"
49,V,int64,0,0.00,15,0,17,"[0, 2]"
50,V100,float64,10371,73.58,106,5.2,29.9,"[nan, 13.4]"
51,V40,float64,0,0.00,1769,2.9,2840.5,"[154.0, 44.0]"
52,ZN,int64,0,0.00,1552,0,2132,"[75, 652]"
53,Y_LABEL,int64,0,0.00,2,0,1,"[0, 1]"

In [4]:
# percent20UP = list(df_info[df_info['nullPCT'] >= 20.0]['dataFeatures'])
# percent20UP

In [5]:
# df = df.drop(percent20UP,axis=1)
# print(df.shape)

In [6]:
df.head()

,ID,COMPONENT_ARBITRARY,ANONYMOUS_1,YEAR,SAMPLE_TRANSFER_DAY,ANONYMOUS_2,AG,AL,B,BA,BE,CA,CD,CO,CR,CU,FH2O,FNOX,FOPTIMETHGLY,FOXID,FSO4,FTBN,FE,FUEL,H2O,K,LI,MG,MN,MO,NA,NI,P,PB,PQINDEX,S,SB,SI,SN,SOOTPERCENTAGE,TI,U100,U75,U50,U25,U20,U14,U6,U4,V,V100,V40,ZN,Y_LABEL
0,TRAIN_00000,COMPONENT3,1486,2011,7,200,0,3,93,0,0,3059,0.0,0,13,78,NaN,NaN,NaN,NaN,NaN,NaN,888,NaN,0.0,27.0,1,14,16,1,16,6,1951,0,8504,21370,0,427,2,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,154.0,75,0
1,TRAIN_00001,COMPONENT2,1350,2021,51,375,0,2,19,0,0,2978,0.0,0,0,31,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,0.0,NaN,0,1,0,0,1,0,572,2,19,1117,0,0,0,NaN,0,0.0,0.0,1.0,2.0,4.0,6.0,216.0,1454.0,0,NaN,44.0,652,0
2,TRAIN_00002,COMPONENT2,2415,2015,2,200,0,110,1,1,0,17,0.0,0,1,2,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,0.0,0.0,0,0,0,0,2,0,328,0,17,1334,0,0,1,NaN,0,0.0,0.0,0.0,0.0,3.0,39.0,11261.0,41081.0,0,NaN,72.6,412,1
3,TRAIN_00003,COMPONENT3,7389,2010,2,200,0,8,3,0,0,1960,0.0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN,0.0,NaN,0,4,1,0,0,0,906,1,44,21774,2,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,133.3,7,0
4,TRAIN_00004,COMPONENT3,3954,2015,4,200,0,1,157,0,0,71,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,71,NaN,0.0,0.0,0,0,0,0,2,0,309,0,217,18470,0,2,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,133.1,128,0

In [7]:
# show dataframe for each features that we have
dataFeatures = []
dataType     = []
null         = []
nullPCT      = []
unique       = []
minValue     = []
maxValue     = []
uniqueSample = []


for item in list(df):
    dataFeatures.append(item)

for item in dataFeatures:
    dataType.append(df[item].dtype.name)
    
for item in dataFeatures:
    null.append(len(df[df[item].isnull() == True]))

for item in dataFeatures:
    nullPCT.append(round(len(df[df[item].isnull() == True])/len(df[item])*100,2))
    
for item in dataFeatures:
    minValue.append(df[item].min())

for item in dataFeatures:
    maxValue.append(df[item].max())

for item in dataFeatures:
    unique.append(df[item].nunique())

for item in dataFeatures:
    uniqueSample.append(df[item].unique()[0:2])

df_info = pd.DataFrame({
    'dataFeatures' : dataFeatures,
    'dataType' : dataType,
    'null' : null,
    'nullPCT':nullPCT,
    'unique' : unique,
    'minValue' : minValue,
    'maxValue' : maxValue,
    'uniqueSample':uniqueSample
})
df_info

,dataFeatures,dataType,null,nullPCT,unique,minValue,maxValue,uniqueSample
0,ID,object,0,0.00,14095,TRAIN_00000,TRAIN_14094,"[TRAIN_00000, TRAIN_00001]"
1,COMPONENT_ARBITRARY,object,0,0.00,4,COMPONENT1,COMPONENT4,"[COMPONENT3, COMPONENT2]"
2,ANONYMOUS_1,int64,0,0.00,2951,1000,294451,"[1486, 1350]"
3,YEAR,int64,0,0.00,16,2007,2022,"[2011, 2021]"
4,SAMPLE_TRANSFER_DAY,int64,0,0.00,107,0,368,"[7, 51]"
5,ANONYMOUS_2,int64,0,0.00,842,200,9650,"[200, 375]"
6,AG,int64,0,0.00,4,0,3,"[0, 1]"
7,AL,int64,0,0.00,328,0,4630,"[3, 2]"
8,B,int64,0,0.00,504,0,2051,"[93, 19]"
9,BA,int64,0,0.00,38,0,216,"[0, 1]"
10,BE,int64,0,0.00,9,0,9,"[0, 6]"
11,CA,int64,0,0.00,2581,0,6609,"[3059, 2978]"
12,CD,float64,1394,9.89,6,0.0,18.0,"[0.0, nan]"
13,CO,int64,0,0.00,10,0,27,"[0, 1]"
14,CR,int64,0,0.00,102,0,2398,"[13, 0]"
15,CU,int64,0,0.00,496,0,5701,"[78, 31]"
16,FH2O,float64,10205,72.40,72,6.0,320.0,"[nan, 9.0]"
17,FNOX,float64,10205,72.40,21,3.0,38.0,"[nan, 5.0]"
18,FOPTIMETHGLY,float64,10205,72.40,8,0.0,13.0,"[nan, 0.0]"
19,FOXID,float64,10205,72.40,34,4.0,68.0,"[nan, 9.0]"
20,FSO4,float64,10205,72.40,35,10.0,68.0,"[nan, 18.0]"
21,FTBN,float64,10205,72.40,99,0.0,27.7,"[nan, 8.9]"
22,FE,int64,0,0.00,1281,0,31706,"[888, 2]"
23,FUEL,float64,10205,72.40,21,0.0,12.0,"[nan, 0.0]"
24,H2O,float64,0,0.00,47,0.0,52.7,"[0.0, 0.1]"
25,K,float64,2299,16.31,102,0.0,705.0,"[27.0, nan]"
26,LI,int64,0,0.00,36,0,117,"[1, 0]"
27,MG,int64,0,0.00,554,0,1509,"[14, 1]"
28,MN,int64,0,0.00,100,0,877,"[16, 0]"
29,MO,int64,0,0.00,298,0,419,"[1, 0]"
30,NA,int64,0,0.00,83,0,1212,"[16, 1]"
31,NI,int64,0,0.00,57,0,176,"[6, 0]"
32,P,int64,0,0.00,2191,2,3102,"[1951, 572]"
33,PB,int64,0,0.00,73,0,736,"[0, 2]"
34,PQINDEX,int64,0,0.00,1910,0,56761,"[8504, 19]"
35,S,int64,0,0.00,8076,386,64160,"[21370, 1117]"
36,SB,int64,0,0.00,38,0,103,"[0, 2]"
37,SI,int64,0,0.00,514,0,5459,"[427, 0]"
38,SN,int64,0,0.00,37,0,289,"[2, 0]"
39,SOOTPERCENTAGE,float64,10205,72.40,55,0.0,6.5,"[nan, 0.2]"
40,TI,int64,0,0.00,71,0,403,"[5, 0]"
41,U100,float64,11779,83.57,14,0.0,18.0,"[nan, 0.0]"
42,U75,float64,11779,83.57,20,0.0,33.0,"[nan, 0.0]"
43,U50,float64,11779,83.57,90,0.0,939.0,"[nan, 1.0]"
44,U25,float64,11779,83.57,195,0.0,1651.0,"[nan, 2.0]"
45,U20,float64,11779,83.57,275,0.0,2932.0,"[nan, 4.0]"
46,U14,float64,11977,84.97,549,0.0,11296.0,"[nan, 6.0]"
47,U6,float64,11977,84.97,1766,15.0,412627.0,"[nan, 216.0]"
48,U4,float64,11977,84.97,2053,154.0,844421.0,"[nan, 1454.0]"
49,V,int64,0,0.00,15,0,17,"[0, 2]"
50,V100,float64,10371,73.58,106,5.2,29.9,"[nan, 13.4]"
51,V40,float64,0,0.00,1769,2.9,2840.5,"[154.0, 44.0]"
52,ZN,int64,0,0.00,1552,0,2132,"[75, 652]"
53,Y_LABEL,int64,0,0.00,2,0,1,"[0, 1]"

In [8]:
# dfID    = df[['ID','COMPONENT_ARBITRARY']]
# dfFull  = df.drop(['ID','COMPONENT_ARBITRARY'],axis=1)
# print(dfFull.shape)

In [9]:
percent20UP = list(df_info[df_info['nullPCT'] >= 20.0]['dataFeatures'])
percent20UP

['FH2O',
 'FNOX',
 'FOPTIMETHGLY',
 'FOXID',
 'FSO4',
 'FTBN',
 'FUEL',
 'SOOTPERCENTAGE',
 'U100',
 'U75',
 'U50',
 'U25',
 'U20',
 'U14',
 'U6',
 'U4',
 'V100']

In [10]:
df = df.drop(percent20UP,axis=1)
print(df.shape)

(14095, 37)

# Imputed

In [11]:
# from sklearn.impute import KNNImputer

# imputer = KNNImputer(n_neighbors=3)
# result  = imputer.fit_transform(dfFull)

In [12]:
# dff = pd.DataFrame(result, columns=dfFull.columns)
# dff[['ID','COMPONENT_ARBITRARY']] = dfID
# dff = dff[df.columns]
# dff.head()

# Split

In [13]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

In [ ]:
categorical_features = ['COMPONENT_ARBITRARY', 'YEAR']
# Inference(실제 진단 환경)에 사용하는 컬럼
test_stage_features = ['COMPONENT_ARBITRARY', 'ANONYMOUS_1', 'YEAR' , 'ANONYMOUS_2', 'AG', 'CO', 'CR', 'CU', 'FE', 'H2O', 'MN', 'MO', 'NI', 'PQINDEX', 'TI', 'V', 'V40', 'ZN']

In [ ]:
# get dummies
dff = df.dropna()
dff = pd.get_dummies(dff,columns=['COMPONENT_ARBITRARY'])

In [16]:
# data split
clftarget = 'Y_LABEL'
features_for_clfmodel = [f for f in list(dff) if f not in [clftarget,'ID']]


# data split
from sklearn.model_selection import train_test_split
clfX_train, clfX_test, clfy_train, clfy_test = train_test_split(dff[features_for_clfmodel], 
                                                 dff[clftarget], 
                                                 test_size=0.2, 
                                                 random_state=101,stratify=dff['Y_LABEL'])

In [18]:
clfmodel = XGBClassifier(random_state=101)
clfmodel.fit(clfX_train,clfy_train)

/opt/conda/lib/python3.8/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[12:31:14] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=80,
              num_parallel_tree=1, predictor='auto', random_state=101,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [19]:
clfprediction = clfmodel.predict(clfX_test)

In [20]:
from sklearn.metrics import classification_report

In [21]:
print(classification_report(clfy_test,clfprediction))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98      1915
           1       0.89      0.49      0.64       166

    accuracy                           0.95      2081
   macro avg       0.92      0.74      0.81      2081
weighted avg       0.95      0.95      0.95      2081

In [22]:
clfprediction = clfmodel.predict(clfX_test)

In [23]:
big_proba = clfmodel.predict_proba(dff[features_for_clfmodel])[:,0]

In [24]:
len(big_proba)

10402

In [26]:
dff

,ID,ANONYMOUS_1,YEAR,SAMPLE_TRANSFER_DAY,ANONYMOUS_2,AG,AL,B,BA,BE,CA,CD,CO,CR,CU,FE,H2O,K,LI,MG,MN,MO,NA,NI,P,PB,PQINDEX,S,SB,SI,SN,TI,V,V40,ZN,Y_LABEL,COMPONENT_ARBITRARY_COMPONENT1,COMPONENT_ARBITRARY_COMPONENT2,COMPONENT_ARBITRARY_COMPONENT3,COMPONENT_ARBITRARY_COMPONENT4
0,TRAIN_00000,1486,2011,7,200,0,3,93,0,0,3059,0.0,0,13,78,888,0.0,27.0,1,14,16,1,16,6,1951,0,8504,21370,0,427,2,5,0,154.0,75,0,0,0,1,0
2,TRAIN_00002,2415,2015,2,200,0,110,1,1,0,17,0.0,0,1,2,4,0.0,0.0,0,0,0,0,2,0,328,0,17,1334,0,0,1,0,0,72.6,412,1,0,1,0,0
4,TRAIN_00004,3954,2015,4,200,0,1,157,0,0,71,0.0,0,0,0,71,0.0,0.0,0,0,0,0,2,0,309,0,217,18470,0,2,0,0,0,133.1,128,0,0,0,1,0
6,TRAIN_00006,1416,2015,7,616,0,0,21,0,0,130,0.0,0,0,3,35,0.0,0.0,0,0,0,0,2,0,330,0,26,16280,0,1,0,0,0,148.5,24,0,0,0,1,0
7,TRAIN_00007,1170,2009,4,370,0,5,3,3,0,2589,0.0,0,3,6,81,0.0,2.0,1,0,2,1,5,0,866,2,7735,17090,1,6,0,0,0,142.9,16,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,TRAIN_14087,1192,2014,15,200,0,5,24,2,0,2577,0.0,0,0,0,9,0.0,2.0,0,13,0,0,3,0,938,0,11,11920,0,6,0,0,0,106.2,1204,0,1,0,0,0
14088,TRAIN_14088,1311,2010,6,511,0,0,20,0,0,227,0.0,0,0,8,43,0.0,0.0,0,1,0,0,1,0,967,0,16,18840,0,2,0,0,0,128.9,20,0,0,0,1,0
14090,TRAIN_14090,1616,2014,8,200,0,2,201,1,0,6,0.0,0,0,3,23,0.0,1.0,0,0,0,0,8,0,477,0,35,22000,0,2,0,0,0,135.4,16,0,0,0,1,0
14091,TRAIN_14091,2784,2013,2,200,0,3,85,0,0,2945,0.0,0,0,2,12,0.0,4.0,0,36,0,224,3,0,1163,1,9,5494,0,5,0,0,0,117.5,1408,0,1,0,0,0
14094,TRAIN_14094,1902,2012,15,200,0,0,77,0,0,494,0.0,0,0,110,10,0.0,0.0,0,1,0,0,2,0,424,2,81,2057,0,6,0,2,0,47.0,612,0,0,1,0,0

In [27]:
dff['big_proba'] = big_proba

In [28]:
dff

,ID,ANONYMOUS_1,YEAR,SAMPLE_TRANSFER_DAY,ANONYMOUS_2,AG,AL,B,BA,BE,CA,CD,CO,CR,CU,FE,H2O,K,LI,MG,MN,MO,NA,NI,P,PB,PQINDEX,S,SB,SI,SN,TI,V,V40,ZN,Y_LABEL,COMPONENT_ARBITRARY_COMPONENT1,COMPONENT_ARBITRARY_COMPONENT2,COMPONENT_ARBITRARY_COMPONENT3,COMPONENT_ARBITRARY_COMPONENT4,big_proba
0,TRAIN_00000,1486,2011,7,200,0,3,93,0,0,3059,0.0,0,13,78,888,0.0,27.0,1,14,16,1,16,6,1951,0,8504,21370,0,427,2,5,0,154.0,75,0,0,0,1,0,0.998415
2,TRAIN_00002,2415,2015,2,200,0,110,1,1,0,17,0.0,0,1,2,4,0.0,0.0,0,0,0,0,2,0,328,0,17,1334,0,0,1,0,0,72.6,412,1,0,1,0,0,0.001921
4,TRAIN_00004,3954,2015,4,200,0,1,157,0,0,71,0.0,0,0,0,71,0.0,0.0,0,0,0,0,2,0,309,0,217,18470,0,2,0,0,0,133.1,128,0,0,0,1,0,0.998567
6,TRAIN_00006,1416,2015,7,616,0,0,21,0,0,130,0.0,0,0,3,35,0.0,0.0,0,0,0,0,2,0,330,0,26,16280,0,1,0,0,0,148.5,24,0,0,0,1,0,0.999849
7,TRAIN_00007,1170,2009,4,370,0,5,3,3,0,2589,0.0,0,3,6,81,0.0,2.0,1,0,2,1,5,0,866,2,7735,17090,1,6,0,0,0,142.9,16,0,0,0,1,0,0.998795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,TRAIN_14087,1192,2014,15,200,0,5,24,2,0,2577,0.0,0,0,0,9,0.0,2.0,0,13,0,0,3,0,938,0,11,11920,0,6,0,0,0,106.2,1204,0,1,0,0,0,0.999717
14088,TRAIN_14088,1311,2010,6,511,0,0,20,0,0,227,0.0,0,0,8,43,0.0,0.0,0,1,0,0,1,0,967,0,16,18840,0,2,0,0,0,128.9,20,0,0,0,1,0,0.999398
14090,TRAIN_14090,1616,2014,8,200,0,2,201,1,0,6,0.0,0,0,3,23,0.0,1.0,0,0,0,0,8,0,477,0,35,22000,0,2,0,0,0,135.4,16,0,0,0,1,0,0.999680
14091,TRAIN_14091,2784,2013,2,200,0,3,85,0,0,2945,0.0,0,0,2,12,0.0,4.0,0,36,0,224,3,0,1163,1,9,5494,0,5,0,0,0,117.5,1408,0,1,0,0,0,0.999092
14094,TRAIN_14094,1902,2012,15,200,0,0,77,0,0,494,0.0,0,0,110,10,0.0,0.0,0,1,0,0,2,0,424,2,81,2057,0,6,0,2,0,47.0,612,0,0,1,0,0,0.998031

In [32]:
dff['YEAR'].dtype

dtype('int64')

In [ ]:
# Inference(실제 진단 환경)에 사용하는 컬럼
test_stage_features = ['COMPONENT_ARBITRARY', 'ANONYMOUS_1', 'YEAR' , 'ANONYMOUS_2', 'AG', 'CO', 'CR', 'CU', 'FE', 'H2O', 'MN', 'MO', 'NI', 'PQINDEX', 'TI', 'V', 'V40', 'ZN']

In [29]:
import xgboost as xgb


# data split
rgtarget = 'big_proba'
features_for_rgmodel = [f for f in list(dff) if f not in [rgtarget,'ID','Y_LABEL']]


# data split
from sklearn.model_selection import train_test_split
rgX_train, rgX_test, rgy_train, rgy_test = train_test_split(dff[features_for_rgmodel], 
                                                 dff[rgtarget], 
                                                 test_size=0.2, 
                                                 random_state=101)

In [30]:
rgmodel = xgb.XGBRegressor(random_state=101)
rgmodel.fit(rgX_train,rgy_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=80,
             num_parallel_tree=1, predictor='auto', random_state=101,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [ ]:
rgprediction = rgmodel.predict(rgX_test)

In [31]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print('MAE: ' + mean_absolute_error(rgy_test,rgprediction))
print('MSE: ' + mean_squared_error(rgy_test, rgprediction))
print('R2_Score: ' + r2_score(rgy_test, rgprediction))

ImportError: cannot import name 'accuracy' from 'sklearn.metrics' (/root/.local/lib/python3.8/site-packages/sklearn/metrics/__init__.py)

In [ ]:
print(accuracy(rgy_test,rgprediction))